language: go

go:
  - "1.11.x"

install:
  - cd ..
  - cd ..
  - git clone https://github.com/satori/go.uuid.git
  - git checkout 879c5887cd475cd7864858769793b2ceb0d44feb
  - cd kerti/idcra-api
  - go generate ./schema
  - go get -v ./...