language: go

go:
  - "1.11.x"

install:
  - cd ../..
  - mkdir satori
  - cd satori
  - git clone https://github.com/satori/go.uuid.git
  - cd go.uuid
  - git checkout 879c5887cd475cd7864858769793b2ceb0d44feb
  - cd ../../kerti/idcra-api
  - go generate ./schema
  - go get -v ./...