language: go
sudo: false
go:
  - "1.11.x"
before_install:
  - go get github.com/mattn/goveralls
  - go get golang.org/x/tools/cmd/cover
install:
  - go get -u github.com/jteeuwen/go-bindata/...
  - cd ../..
  - mkdir satori
  - cd satori
  - git clone https://github.com/satori/go.uuid.git
  - cd go.uuid
  - git checkout 879c5887cd475cd7864858769793b2ceb0d44feb
  - cd ../../kerti/idcra-api
  - go generate ./schema
  - go get -t -v ./...
script:
  - go build server.go
  - $HOME/gopath/bin/goveralls -service=travis-ci
notifications:
  email: false